# Change these first
owner: PauloGoncalvesBH # Your GitHub username
repo: serverest-status-uptime # Your Github repository name

# Add your sites here
sites:
  - name: ServeRest.dev
    url: http://serverest.dev/
    maxResponseTime: 3000

assignees:
  - PauloGoncalvesBH

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /$REPO
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ServeRest Status
  introTitle: Monitoramento em tempo real do status e tempo de atividade do [ServeRest.dev](http://serverest.dev/)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: ServeRest
      href: https://github.com/PauloGoncalvesBH/ServeRest

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
