# Change these first
owner: ServeRest # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: ServeRest.dev
    url: http://serverest.dev/
    maxResponseTime: 1500
  - name: API /usuarios
    url: http://serverest.dev/usuarios
    headers:
      - "monitor: uptime"
    maxResponseTime: 600
  - name: API /carrinhos
    url: http://serverest.dev/carrinhos
    headers:
      - "monitor: uptime"
    maxResponseTime: 600
  - name: API /produtos
    url: http://serverest.dev/produtos
    headers:
      - "monitor: uptime"
    maxResponseTime: 600

assignees:
  - PauloGoncalvesBH

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.serverest.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://user-images.githubusercontent.com/29241659/115503421-c7e7bf00-a24c-11eb-8381-cca0ef8d867c.png
  name: ServeRest Status
  navbar:
    - title: Status
      href: /
    - title: ServeRest
      href: https://github.com/$OWNER/ServeRest
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 */12 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
