# Change these first
owner: PauloGoncalvesBH # Your GitHub username
repo: serverest-status-uptime # Your Github repository name

# Add your sites here
sites:
  - name: ServeRest.dev
    url: http://serverest.dev/
    maxResponseTime: 600
  - name: API /usuarios
    url: http://serverest.dev/usuarios
    headers:
      - "monitor: uptime"
    maxResponseTime: 600
  - name: API /carrinhos
    url: http://serverest.dev/carrinhos
    headers:
      - "monitor: uptime"
    maxResponseTime: 600
  - name: API /produtos
    url: http://serverest.dev/produtos
    headers:
      - "monitor: uptime"
    maxResponseTime: 600

assignees:
  - PauloGoncalvesBH

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /serverest-status-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ServeRest Status
  navbar:
    - title: ServeRest Status [GitHub] 
      href: https://github.com/PauloGoncalvesBH/serverest-status-uptime
    - title: ServeRest [GitHub]
      href: https://github.com/PauloGoncalvesBH/ServeRest

workflowSchedule:
  graphs: "0 */12 * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
